### ISSUE TITLE
World shuts down at random

### ISSUE THREAD

**Issue by Alatarius** [mt-mods/plantlife_modpack#60] opened 2023-09-25 18:31 UTC
Just as the title says. I will be doing something and then my world will shutdown randomly with this error:
```lua
AsyncErr: Lua: Runtime error from mod 'youngtrees' in callback environment_OnGenerated(): ...netest\bin\..\mods\plantlife_modpack\youngtrees\init.lua:137: attempt to concatenate upvalue 'did' (a nil value)
stack traceback:
	...netest\bin\..\mods\plantlife_modpack\youngtrees\init.lua:137: in function <...netest\bin\..\mods\plantlife_modpack\youngtrees\init.lua:133>
	D:\Games\Minetest\bin\..\builtin\game\register.lua:446: in function <D:\Games\Minetest\bin\..\builtin\game\register.lua:432>
```

**Comment by wsor4035** [comment] 2023-09-25 22:22
do you have the full modpack enabled, or parts? in theory the function can fail, but it really shouldnt. the reason it randomly shutsdown is because im guessing mapgen is triggered somewhere

**Comment by wsor4035** [comment] 2023-09-25 22:23
we could add an assert to make sure that did is initialized, but that wont fix the underlying issue

**Comment by Alatarius** [comment] 2023-09-26 04:17
> do you have the full modpack enabled, or parts?
I have whatever was on cdb
> 
> edit: are you using regular lua, or luajit?
I don't understand this question. I just play the regular minetest game if that helps.

**Comment by Niklp09** [comment] 2023-09-26 10:58
The default windows builds use LuaJIT 2.1-beta3 (from 2017)

**Comment by Alatarius** [comment] 2023-09-26 13:52
Then I am using LuaJit since I'm running it on Windows 11

⁣Get BlueMail for Android ​

**Comment by wsor4035** [comment] 2023-10-26 16:02
@Alatarius since i cant reproduce this issue, could you install the worldedit mod, and run the following command
`//lua minetest.chat_send_all(dump(minetest.registered_decorations["youngtrees:youngtree"]))` and report back here what it outputs?

**Comment by wsor4035** [comment] 2023-10-26 16:05
additionally, what other mods do you have enabled in this world?

**Comment by Alatarius** [comment] 2023-10-28 18:10
> @Alatarius since i cant reproduce this issue, could you install the worldedit mod, and run the following command `//lua minetest.chat_send_all(dump(minetest.registered_decorations["youngtrees:youngtree"]))` and report back here what it outputs?

It tells me that that is an invalid command, I have all permissions enabled (used /grantme all)

**Comment by Alatarius** [comment] 2023-10-28 18:20
> additionally, what other mods do you have enabled in this world?

Here is my list:
3d_apple, 3d_armor, ambience, amethyst_new, animalworld, anvil, area_containers, artdeco, auroras, awards, bakedclay, banner, basic_materials, beds, biofuel, biomeinfo, biome_lib, bonemeal, bows, bricks_plus, bucket, bucket_wooden, builtin_item, carpets, castle_farming, castle_gates, castle_lighting, castle_masonry, castle_shields, castle_storage, castle_tapestries, castle_weapons, connected_chests, controls, cottages, cracked_castle, craftguide, darkage, decorations_sea, deepslate, diggicontrol, digilines, digistuff, digtron, display_modpack, doc, doc_basics, doc_encyclopedia, doc_identifier, doc_items, doors, drinks, ebiomes, ethereal, etherium_stuff, everness, factory_bridges, farming, flowerpot, geodes_lib, glass_stained, handle_schematics, hangglider, hopper, illumination, itemframes, item_drop, leads, leather_armor, livingcaves, livingcavesmobs, livingdesert, livingfloatlands, livingjungle, livingnether, loot, lwcomponents, lwscratch, marinara, marinaramobs, mesecons, mesecons_carts, mesecons_x, micupack, minecart, mobkit, mobs, mobs_monster, mobs_skeletons, mobs_sky, mobs_water, mob_horse, modlib, modname_tooltip, modutil, moreblocks, moredecorations, morelights, moreores, moretorches, moretrees, music_modpack, nativevillages, naturalbiomes, nether, new_campfire, obsidianstuff, paintings_gallery, paintings_lib, pipeworks, pipunhole, plantlife_modpack, plaster, powerbanks, redef, regrowing_fruits, rnd, ropes, scaffolding, servercleaner, shallow_ores, signs_lib, simple_furniture, skinsdb, slats, stackslabs, stainedglass, stripped_tree, sugar, swamp, technic_plus, technic_recipes, techpack, tga_encoder, torch_bomb, tpad, ts_furniture, tt, tubelib2, unifieddyes, unified_inventory, variety, visible_sneak, void_chest, we_undo, wilhelminessounds, wine, woodcutting, worldedit, worldedit_hud_helper, xdecor, xmaps, x_enchanting, x_farming

**Comment by lbaudroit** [comment] 2023-10-30 05:05
I had a similar problem (world shutting down when I started it), so I tested removing each mod I had in common with Alatarius. It stopped shutting down when I disabled "ebiomes"

**Comment by wsor4035** [comment] 2023-10-30 05:31
we have a winner https://github.com/CowboyLva/ebiomes/blob/09e699d941dd1b058ace6e4819e1782fb510e8cf/rereg.lua#L1154 irresponsibly calling the clear function and not cleaning up the mess they created.

thanks @lbaudroit

**Closed** 2023-11-03 20:20 UTC
Labels: bug
